name: bebia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
isar_version: &isar_version 3.3.2

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  isar_community:
    version: *isar_version
  isar_community_flutter_libs:
    version: *isar_version
  path_provider: ^2.1.5
  path: ^1.9.1
  record: ^6.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_community_generator:
    version: *isar_version
  build_runner: ^2.7.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true